import { FastifyInstance } from "fastify";
import { eq } from "drizzle-orm";
import { promises as fs } from "node:fs";
import { resolve as pathResolve } from "node:path";
import { db } from "../db/index.js";
import { agents } from "../db/schema.js";
import { config } from "../lib/config.js";

// A one-liner the operator runs on the host where their Hermes agent already
// lives. It:
//   1. resolves HERMES_HOME (either from env or from the Hermes config)
//   2. drops the CircleChat skill template into skills/circlechat/
//   3. drops the MCP bridge script into scripts/circlechat-mcp.mjs
//   4. registers the MCP server with `hermes mcp add circlechat ...`
//   5. writes .circlechat-managed.json so the Skills UI recognises the pack
//
// The endpoint is token-authed (bot token in query) so the script itself can
// run anywhere `curl` reaches the CC API — including from the operator's
// laptop or their own Pi.

const SKILL_TEMPLATE =
  process.env.CC_SKILL_TEMPLATE ?? pathResolve(process.cwd(), "templates/circlechat-skill");
const MCP_SCRIPT_PATH =
  process.env.CC_MCP_SCRIPT ?? pathResolve(process.cwd(), "scripts/circlechat-mcp.mjs");

export default async function agentAttachRoutes(app: FastifyInstance): Promise<void> {
  // Public — no session required. Token passed as ?token=... and validated
  // against agents.bot_token. Returns a bash script as text/plain.
  app.get("/public/attach-install/:agentId", async (req, reply) => {
    const { agentId } = req.params as { agentId: string };
    const { token } = req.query as { token?: string };
    if (!token) {
      reply.code(400).type("text/plain").send("missing token");
      return;
    }
    const [a] = await db.select().from(agents).where(eq(agents.id, agentId)).limit(1);
    if (!a || a.botToken !== token) {
      reply.code(401).type("text/plain").send("invalid token");
      return;
    }

    const skillMd = await fs.readFile(
      pathResolve(SKILL_TEMPLATE, "DESCRIPTION.md"),
      "utf8",
    );
    const mcpScript = await fs.readFile(MCP_SCRIPT_PATH, "utf8");

    const apiBase = `${config.publicBaseUrl}/api`;
    const script = renderInstallScript({
      botToken: a.botToken,
      agentHandle: a.handle,
      apiBase,
      skillMd,
      mcpScript,
    });

    reply.type("text/plain; charset=utf-8").send(script);
  });

  // Convenience JSON version for UIs that want to render the files inline.
  app.get("/agents/:agentId/attach-bundle", async (req, reply) => {
    const { agentId } = req.params as { agentId: string };
    const { token } = req.query as { token?: string };
    if (!token) return reply.code(400).send({ error: "missing_token" });
    const [a] = await db.select().from(agents).where(eq(agents.id, agentId)).limit(1);
    if (!a || a.botToken !== token) return reply.code(401).send({ error: "invalid_token" });
    const skillMd = await fs.readFile(
      pathResolve(SKILL_TEMPLATE, "DESCRIPTION.md"),
      "utf8",
    );
    const mcpScript = await fs.readFile(MCP_SCRIPT_PATH, "utf8");
    return {
      agentHandle: a.handle,
      apiBase: `${config.publicBaseUrl}/api`,
      skillMd,
      mcpScript,
      installCurl: `curl -fsSL '${config.publicBaseUrl}/api/public/attach-install/${a.id}?token=${a.botToken}' | bash`,
    };
  });
}

function renderInstallScript(params: {
  botToken: string;
  agentHandle: string;
  apiBase: string;
  skillMd: string;
  mcpScript: string;
}): string {
  const { botToken, agentHandle, apiBase, skillMd, mcpScript } = params;
  // The script embeds the skill + MCP source via heredoc. Everything is
  // quoted so the values can't break out. All paths are computed on the
  // operator's host; we don't assume anything about theirs.
  return `#!/usr/bin/env bash
# CircleChat attach-install for @${agentHandle}
# Generated by CircleChat. Safe to re-run — all writes are idempotent.
set -euo pipefail

BOT_TOKEN=${shq(botToken)}
AGENT_HANDLE=${shq(agentHandle)}
CC_API_BASE=${shq(apiBase)}

# 1. Resolve HERMES_HOME.
if [ -z "\${HERMES_HOME:-}" ]; then
  if command -v hermes >/dev/null 2>&1; then
    HERMES_HOME="$(hermes config path 2>/dev/null || true)"
  fi
fi
if [ -z "\${HERMES_HOME:-}" ]; then
  HERMES_HOME="$HOME/.hermes"
fi
mkdir -p "$HERMES_HOME"
echo "[attach] HERMES_HOME=$HERMES_HOME"

# 2. Drop the CircleChat skill.
SKILL_DIR="$HERMES_HOME/skills/circlechat"
mkdir -p "$SKILL_DIR"
cat > "$SKILL_DIR/DESCRIPTION.md" <<'__CC_SKILL_EOF__'
${skillMd.replace(/\r/g, "")}
__CC_SKILL_EOF__
echo "[attach] skill written → $SKILL_DIR/DESCRIPTION.md"

# 3. Drop the MCP bridge script.
SCRIPTS_DIR="$HERMES_HOME/circlechat-scripts"
mkdir -p "$SCRIPTS_DIR"
MCP_SCRIPT="$SCRIPTS_DIR/circlechat-mcp.mjs"
cat > "$MCP_SCRIPT" <<'__CC_MCP_EOF__'
${mcpScript.replace(/\r/g, "")}
__CC_MCP_EOF__
chmod +x "$MCP_SCRIPT"
echo "[attach] mcp script written → $MCP_SCRIPT"

# 4a. Quarantine the bundled Hermes skill pack (non-CircleChat). Opt out with
#     CC_QUARANTINE_BUNDLED_SKILLS=0.
QUARANTINE="\${CC_QUARANTINE_BUNDLED_SKILLS:-1}"
if [ "$QUARANTINE" = "1" ]; then
  DISABLED_DIR="$HERMES_HOME/skills-disabled"
  mkdir -p "$DISABLED_DIR"
  for d in "$HERMES_HOME"/skills/*/; do
    [ -d "$d" ] || continue
    name=$(basename "$d")
    [ "$name" = "circlechat" ] && continue
    case "$name" in .*) continue;; esac
    mv "$d" "$DISABLED_DIR/$name" 2>/dev/null && echo "[attach] quarantined skill: $name" || true
  done
fi

# 4. Manifest so the Skills UI treats the pack as CircleChat-managed.
MANIFEST="$HERMES_HOME/skills/.circlechat-managed.json"
if [ -f "$MANIFEST" ]; then
  if ! grep -q '"circlechat"' "$MANIFEST"; then
    # naive but adequate — append before the closing ]
    python3 -c "import json,sys,pathlib; p=pathlib.Path(sys.argv[1]); j=json.loads(p.read_text()); j.append('circlechat'); j=sorted(set(j)); p.write_text(json.dumps(j,indent=2))" "$MANIFEST" 2>/dev/null || echo '["circlechat"]' > "$MANIFEST"
  fi
else
  echo '["circlechat"]' > "$MANIFEST"
fi
echo "[attach] manifest updated"

# 5. Register the MCP server with Hermes.
if command -v hermes >/dev/null 2>&1; then
  # Re-add idempotently.
  HERMES_HOME="$HERMES_HOME" hermes mcp remove circlechat >/dev/null 2>&1 || true
  printf 'y\\n' | HERMES_HOME="$HERMES_HOME" hermes mcp add circlechat \\
    --command node \\
    --args "$MCP_SCRIPT" "$BOT_TOKEN" "$CC_API_BASE" \\
    >/dev/null
  echo "[attach] hermes mcp add ok"
else
  echo "[attach] WARN: hermes CLI not on PATH; skipping mcp add."
  echo "        once installed, run:"
  echo "          hermes mcp add circlechat --command node --args \\\\"
  echo "            \\"$MCP_SCRIPT\\" \\"$BOT_TOKEN\\" \\"$CC_API_BASE\\""
fi

echo "[attach] done. Your Hermes at $HERMES_HOME is now equipped for CircleChat."
`;
}

// Shell-quote for single-quoted strings.
function shq(v: string): string {
  return `'${v.replace(/'/g, `'\\''`)}'`;
}
